package:
  name: datahub
  version: "{{ load_setup_py_data().version }}"

source:
  path: ../

build:
  entry_points:
    - main = datahub.main:main
  noarch: python

requirements:
  build:
    - python
    - numpy
    - h5py
  run:
    - python
    - requests
    - h5py
    - python-dateutil
    - numpy
    - pytz
    - cbor2

#Optional requirements
#    - pyepics
#    - bsread
#    - bitshuffle
#    - pandas
#    - redis
#    - websockets
#    - matplotlib

about:
  home: https://github.com/paulscherrerinstitute/datahub
  license: GPLv3
